name: chatboxx_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
yarucinnamon: ^0.0.0-dev.10
async: ^2.11.0

environment:
  sdk: ">=2.17.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.2
  action_slider: ^0.7.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lint: ^2.1.1
cupertino_icons: ^1.0.8
dynamic_fonts: ^2.2.1
english_words: ^4.0.0
modal_bottom_sheet: ^3.0.0

flutter_svg: ^2.0.16
material_color_utilities: ^0.11.1
boolean_selector: ^2.1.1
characters: ^1.3.0
clock: ^1.1.1
collection: ^1.18.0
fake_async: ^1.3.1
flutter_lints: ^2.0.3
leak_tracker: ^10.0.5
leak_tracker_flutter_testing: ^3.0.5
matcher: ^0.12.16+1
meta: ^1.15.0
vector: ^1.1.1
vm_service: ^14.2.5
test_api: ^0.7.2
term_glyph: ^1.2.1
string_scanner: ^1.2.0


linter:
  rules:
    - use_super_parameters


flutter:
  uses-material-design: true
  assets:
    - assets/images/